#!/usr/bin/bash

# qpeek
# Oliver Thomson Brown
# 2016-06-23
# simplified bash implementation of qpeek
# based on qpeek by Ohio Supercomputer Centre
# Troy Baer (C) 2001
#
# USAGE
# qpeek -{c|h|t} job_ID
#
# You can find the job_ID for your job using qstat.
#
# Options:
#	-c		Use the cat tool - will return the entire outfile.
#	-h		Use the head tool - will return the first ten lines of the outfile.
#	-t		Use the tail tool - will return the last ten lines of the outfile.
# 
# Use man TOOL to find more information on each tool.

if [ $1 == --help -o $1 == -help ]
	then
		head -n20 $0 | tail -n18
		exit 0
fi

# constants
declare -r SPOOL=/var/spool/torque/spool/
declare -r HOST=eps.hw.ac.uk
declare -r EXT=OU

# build absolute path to outfile
FNAME=${SPOOL}${2}.${HOST}.${EXT}

# check that FNAME exists!
if [ ! -f $FNAME ]
	then
		echo "Cannot resolve outfile, or it is not a file."
		exit -1
elif [ ! -r $FNAME ]
	then 
		echo "Outfile is not readable."
		exit -1
fi

# select requested tool
case $1 in
	-c)
		TOOL=cat
		;;
	-h)
		TOOL=head
		;;
	-t)
		TOOL=tail
		;;
	*)
		echo "Unknown option -- see usage."
		exit -1
esac

# put together
$TOOL $FNAME

exit 0
